language:
  - python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - pip install -r requirements.txt

script:
  - py.test -vv images.py
  - pep8 app.py
  - pep8 images.py

notifications:
  email: false
