language:
  - python

python:
  - 2.7
  - 3.6

install:
  - pip install -r requirements.txt

script:
  - pep8 --ignore=E501 cicero.py
  - pep8 --ignore=E501 cicero
  - py.test cicero/*

notifications:
  email: false
