language:
  - python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - pip install -r requirements.txt

script:
  - py.test -vv images.py
  - pep8 --ignore=E501 images.py
  - pep8 --ignore=E501 cicero.py
  - pep8 --ignore=E501 github_app.py
  - pep8 --ignore=E501 preview_app.py

notifications:
  email: false
